//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneOtoDBEntities1 : DbContext
    {
        public KutuphaneOtoDBEntities1()
            : base("name=KutuphaneOtoDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GorevliBilgi> GorevliBilgi { get; set; }
        public virtual DbSet<UyeBilgi> UyeBilgi { get; set; }
        public virtual DbSet<Kitaplar> Kitaplar { get; set; }
    }
}
