//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOto
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeBilgi
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string TC { get; set; }
        public string NUMARA { get; set; }
        public string MAİL { get; set; }
        public string SİFRE { get; set; }
    }
}
