//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public int ID { get; set; }
        public string ISBN { get; set; }
        public string AD { get; set; }
        public string YAZAR { get; set; }
        public string YAYINEVİ { get; set; }
        public Nullable<System.DateTime> BASIM_TARİHİ { get; set; }
        public Nullable<int> SAYFA_SAYISI { get; set; }
    }
}
